// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { RootGetResponse, ItemsItemsGetResponse } from './types.gen';

/**
 * Root
 * @returns unknown Successful Response
 * @throws ApiError
 */
export const rootGet = (): CancelablePromise<RootGetResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/'
}); };

/**
 * Items
 * @returns Item Successful Response
 * @throws ApiError
 */
export const itemsItemsGet = (): CancelablePromise<ItemsItemsGetResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/items'
}); };