// This file is auto-generated by @hey-api/openapi-ts

export type Item = {
    name: string;
    price: number;
    stocked?: boolean;
};

export type RootGetResponse = unknown;

export type ItemsItemsGetResponse = Array<Item>;

export type $OpenApiTs = {
    '/': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
    '/items': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: Array<Item>;
            };
        };
    };
};